export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const TOGGLE_LOADING_STATE = 'TOGGLE_LOADING_STATE';

export const FETCH_INGREDIENTS_START = 'FETCH_INGREDIENTS_START'
export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS'
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL'
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS'
